apiVersion: v1
kind: ReplicationController

metadata:
  name: edxapp-controller
  labels:
    name: edxapp

spec:
  replicas: 1
  selector:
    name: edxapp
  template:
    metadata:
      labels:
        name: edxapp
    spec:
      containers:
      - name: edxapp
        image: us.gcr.io/appsemblerx/edx-multi-edxapp
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - name: nginx-cert
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: nginx-cert
        secret:
          secretName: nginx-cert
