apiVersion: v1
kind: ReplicationController
metadata:
  name: memcached-controller
  labels:
    name: memcached
spec:
  replicas: 1
  selector: 
    name: memcached
  template:
    metadata:
      labels:
        name: memcached
    spec:
      containers:
      - name: memcached
        image: us.gcr.io/appsemblerx/edx-multi-memcached
        ports:
        - name: memcached
          containerPort: 11211
