# Makes necessary changes to enable running edX inside a Docker container
---
- name: Create runit service folders
  file: 
    path=/etc/service/{{ item }}/control
    state=directory
  with_items: runit_{{version}}_services
  tags: runit

- name: Copy runit scripts
  template: 
    src={{item}}.j2
    dest=/etc/service/{{ item }}/run
    mode=0755
  with_items: runit_{{version}}_services
  tags: runit

- name: Copy runit stop scripts
  template: 
    src={{item}}-stop.j2
    dest=/etc/service/{{ item }}/control/d
    mode=0755
  with_items: runit_{{version}}_services_stop
  tags: runit

- name: Link init.d scripts to runit
  file:
    src=/usr/bin/sv
    path=/etc/init.d/{{ item }}
    state=link
    force=true
  with_items: runit_{{version}}_services
  tags: runit
