XQUEUE_NGINX_PORT: 18040

XQUEUE_RABBITMQ_USER: 'xqueue'
XQUEUE_RABBITMQ_PASS: 'xqueue'
XQUEUE_RABBITMQ_HOSTNAME: 'rabbitmq'

XQUEUE_MYSQL_DB_NAME: 'xqueue'
XQUEUE_MYSQL_USER: 'xqueue'
XQUEUE_MYSQL_PASSWORD: 'xqueue'
XQUEUE_MYSQL_HOST: 'mysql'
XQUEUE_MYSQL_PORT: '3306'
