xqueue_version: 'named-release/cypress'
XQUEUE_NGINX_PORT: 18040

XQUEUE_RABBITMQ_USER: 'edx'
XQUEUE_RABBITMQ_PASS: 'edx'
XQUEUE_RABBITMQ_HOSTNAME: 'rabbitmq'

XQUEUE_MYSQL_DB_NAME: 'xqueue'
XQUEUE_MYSQL_USER: 'xqueue001'
XQUEUE_MYSQL_PASSWORD: 'password'
XQUEUE_MYSQL_HOST: 'mysql'
XQUEUE_MYSQL_PORT: '3306'
