---

- name: "Create jenkins env file"
  template:
    src: "jenkins_env.j2"
    dest: "{{ JENKINS_ANALYTICS_HOME }}/jenkins_env"
    owner: jenkins
    group: jenkins
    mode: 0664

- name: "Create pipeline override file"
  template:
    src: "analytics-override.cfg.j2"
    dest: "{{ JENKINS_ANALYTICS_HOME }}/analytics-override.cfg"
    owner: jenkins
    group: jenkins
    mode: 0664

- name: "Create pipeline emr-vars.yml file"
  template:
    src: "emr-vars.yml.j2"
    dest: "{{ JENKINS_ANALYTICS_HOME }}/emr-vars.yml"
    owner: jenkins
    group: jenkins
    mode: 0664

- name: Checkout edx-analytics-configuration repo
  git:
    dest: "{{ JENKINS_ANALYTICS_EDX_ANALYTICS_CONFIGURATION_CODE_DIR }}"
    repo: "{{ JENKINS_ANALYTICS_EDX_ANALYTICS_CONFIGURATION_SOURCE_REPO }}"
    version: "{{ JENKINS_ANALYTICS_EDX_ANALYTICS_CONFIGURATION_VERSION }}"
    accept_hostkey: yes
  become: true
  become_user: jenkins

- name: Checkout edx-analytics-pipeline repo
  git:
    dest: "{{ JENKINS_ANALYTICS_EDX_ANALYTICS_PIPELINE_CODE_DIR }}"
    repo: "{{ JENKINS_ANALYTICS_EDX_ANALYTICS_PIPELINE_SOURCE_REPO }}"
    version: "{{ JENKINS_ANALYTICS_EDX_ANALYTICS_PIPELINE_VERSION }}"
    accept_hostkey: yes
  become: true
  become_user: jenkins

- name: Create Jenkins working directory
  file:
    path: "{{ JENKINS_ANALYTICS_WORKING_DIR }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Create Jenkins logs directory
  file:
    path: "{{ JENKINS_ANALYTICS_JENKINS_LOGS_DIR }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Create Jenkins venvs directory
  file:
    path: "{{ JENKINS_ANALYTICS_JENKINS_VENVS_DIR }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Create Jenkins analytics configuration venv directory
  file:
    path: "{{ JENKINS_ANALYTICS_EDX_ANALYTICS_CONFIGURATION_VENV_DIR }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Create Jenkins analytics pipeline venv directory
  file:
    path: "{{ JENKINS_ANALYTICS_EDX_ANALYTICS_PIPELINE_VENV_DIR }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755
