---

TRACKING_LOGS_STORAGE_PROVIDER: 'gs'

TRACKING_LOGS_BUCKET: ''
TRACKING_LOGS_DIR: '/edx/var/log/tracking'
TRACKING_LOGS_SENTRY_DSN: ''

# Google Cloud Storage
TRACKING_LOGS_GS_BOTO_FILE: '/root/.boto'
TRACKING_LOGS_GS_DEFAULT_PROJECT_ID: ''
TRACKING_LOGS_GS_SERVICE_KEY_CONTENTS: ''
TRACKING_LOGS_GS_SERVICE_KEY_FILE: '/root/backup-service-account.p12'
TRACKING_LOGS_GS_SERVICE_CLIENT_ID: ''
TRACKING_LOGS_GS_SERVICE_KEY_FILE_PASSWORD: 'notasecret'
