---
- name: Create temp directory
  file: path={{ tmp_dir }} state=directory

- name: Create secret files
  template: src=secret.yml.j2 dest={{ tmp_dir }}/{{ item.name }}.yml mode=0440
  with_items:
    - { name: 'edxapp', secrets_file: "roles/secrets/files/edxapp_secrets.yml" }
    - { name: 'forum', secrets_file: "roles/secrets/files/forum_secrets.yml" }
    - { name: 'mysql-init', secrets_file: "roles/secrets/files/mysql-init_secrets.yml" }
    - { name: 'xqueue', secrets_file: "roles/secrets/files/xqueue_secrets.yml" }

- name: Create secrets in Kubernetes
  command: kubectl create -f {{ tmp_dir }}/{{ item }}.yml
  with_items:
    - edxapp
    - forum
    - mysql-init
    - xqueue
  register: create_result
  failed_when: create_result.rc == 1 and not 'already exists' in create_result.stderr
  changed_when: not 'already exists' in create_result.stderr

- name: Update secrets in Kubernetes
  command: kubectl replace -f {{ tmp_dir }}/{{ item }}.yml
  with_items:
    - edxapp
    - forum
    - mysql-init
    - xqueue

- name: Remove secret files
  file: path={{ tmp_dir }}/{{ item }}.yml state=absent
  with_items:
    - edxapp
    - forum
    - mysql-init
    - xqueue
