# Workaround. What we really want to do is `become_method: sudo su` to run
# tasks as other users. That's not currently possible in Ansible, but may be in
# the future: https://github.com/ansible/ansible/issues/12686. Note that
# modifying /etc/sudoers requires root privileges, so the user running this
# task must already have the ability to sudo as root.
- name: Allow user running the playbook to sudo as other users
  lineinfile: >
    dest=/etc/sudoers state=present
    regexp='^{{ ansible_env.SUDO_USER }} ALL\='
    line='{{ ansible_env.SUDO_USER }} ALL=(ALL) NOPASSWD: ALL'
    validate='visudo -cf %s'
  tags: ['sudo', 'sudo:configuration']

