mysql:
  build: mysql
mongodb:
  build: mongodb
forum:
  build: forum
  links:
    - mongodb:mongo
edxapp:
  build: edxapp
  command: /root/init.sh
  ports:
    - 80
    - 18010
    - 18020
  links:
    - mysql:db
    - mongodb:mongo
    - forum
  tty: true
