apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-controller
  labels:
    name: elasticsearch
spec:
  replicas: 1
  selector: 
    name: elasticsearch
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: appsembler/edx-multi-elasticsearch
        ports:
        - name: elasticsearch
          containerPort: 9200
