apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-controller
  labels:
    name: mysql
spec:
  replicas: 1
  selector: 
    name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        image: appsembler/edx-multi-mysql
        ports:
        - name: mysql
          containerPort: 3306
        - name: memcached
          containerPort: 11211
