---

postgresql_aggregation_packages:
  - libpq-dev
  - postgresql-client

postgresql_aggregation_requirements:
  - psycopg2
POSTGRESQL_AGGREGATION_INSTALL_CRON: false
POSTGRESQL_AGGREGATION_CUSTOMER_NAME: "{{ EDXAPP_PLATFORM_NAME }}"
POSTGRESQL_AGGREGATION_SUBSCRIPTION: "" # 1/1/2015
POSTGRESQL_AGGREGATION_QUOTA: "" # 1000

postgresql_aggregation_login_user: "root"
postgresql_aggregation_login_password: "password"
postgresql_aggregation_login_host: "localhost"
postgresql_aggregation_login_port: 5432

POSTGRESQL_AGGREGATION_HOST: ""
POSTGRESQL_AGGREGATION_DATABASE: ""
POSTGRESQL_AGGREGATION_USER: ""
POSTGRESQL_AGGREGATION_PASSWORD: ""
POSTGRESQL_AGGREGATION_USER_ROLE: ""
POSTGRESQL_AGGREGATION_PORT: 5432
POSTGRESQL_AGGREGATION_OPTIONS: {}

postgresql_aggregation_client_cert: ''
postgresql_aggregation_client_key: ''
postgresql_aggregation_ca_cert: ''
postgresql_aggregation_client_cert_path: '/etc/ssl/certs/postgresql_aggregation-client-cert.pem'
postgresql_aggregation_client_key_path: '/etc/ssl/certs/postgresql_aggregation-client-key.pem'
postgresql_aggregation_ca_cert_path: '/etc/ssl/certs/postgresql_aggregation-server-ca.pem'
postgresql_aggregation_cert_owner: "{{ edxapp_user }}"
postgresql_aggregation_cert_group: "{{ edxapp_user }}"
