- name: Create css directories for microsites
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ edxapp_user }}"
    group: "{{ common_web_group }}"
    mode: "777"
  with_items:
    - { path: "{{ amc_customer_theme_dir }}" }
    - { path: "{{ amc_customer_staticfiles_dir }}" }
  tags:
    - deploy

- name: Make default SiteConfiguration for settings.SITE_ID
  become_user: "{{ edxapp_user }}"
  django_manage: >
      command="lms create_default_site_config"
      app_path="{{ edxapp_code_dir }}"
      settings=amc
      pythonpath="{{ edxapp_code_dir }}"
      virtualenv="{{ edxapp_venv_dir }}"
  tags:
    - deploy

