- name: Create css directories for microsites
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ edxapp_user }}"
    group: "{{ common_web_group }}"
    mode: "755"
  with_items:
    - { path: "{{ amc_customer_theme_dir }}" }
    - { path: "{{ amc_customer_staticfiles_dir }}" }

