---
- name: Install required kernel headers for sysdig
  become: yes
  apt: name="linux-headers-{{ ansible_kernel }}" state=installed
  tags: ['sysdig']

- name: Add Sysdig apt key
  become: yes
  apt_key: url="{{ sysdig_apt_repo_key_url }}" state=present
  tags: ['sysdig']

- name: Add Sysdig apt repo
  become: yes
  apt_repository: repo="{{ sysdig_apt_repo_url }}" state=present
  tags: ['sysdig']

- name: Install Sysdig
  apt: name=sysdig state=latest
  tags: ['sysdig']
