---
galaxy_info:
  author: Amirtds
  description: >
    Get githiub users ssh public keys and add it to the server
  company: Appsembler
  license: BSD
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
  categories:
  - system
