---

- name: install memcached
  apt: >
    pkg=memcached
    state=present

- name: Create memcached configuration file
  template: >
    src=memcached.conf.j2
    dest=/etc/memcached.conf
    owner=root
    group=root
    mode=644
  register: memcached_conf_updated

- name: restart memcached
  service: >
    name=memcached
    state=restarted
  when: memcached_conf_updated.changed
