EDXAPP_LMS_NGINX_PORT: 80

# MySQL
EDXAPP_MYSQL_DB_NAME: 'edxapp'
EDXAPP_MYSQL_USER: 'edxapp001'
EDXAPP_MYSQL_PASSWORD: 'password'
EDXAPP_MYSQL_USER_HOST: '%'
EDXAPP_MYSQL_HOST: 'mysql'
EDXAPP_MYSQL_PORT: '3306'
EDXAPP_MYSQL_USER_ADMIN: "{{ EDXAPP_MYSQL_USER }}"
COMMON_MYSQL_MIGRATE_USER: "{{ EDXAPP_MYSQL_USER }}"
COMMON_MYSQL_MIGRATE_PASS: "{{ EDXAPP_MYSQL_PASSWORD }}"
EDXAPP_MYSQL_PASSWORD_READ_ONLY: "{{ EDXAPP_MYSQL_PASSWORD }}"
EDXAPP_MYSQL_PASSWORD_ADMIN: "{{ EDXAPP_MYSQL_PASSWORD }}"
EDXAPP_MYSQL_PASSWORD_MIGRATE: "{{ EDXAPP_MYSQL_PASSWORD }}"
EDXLOCAL_MYSQL_BIND_IP: 0.0.0.0
EDXLOCAL_MEMCACHED_BIND_IP: 0.0.0.0

COMMON_ENVIRONMENT: "appsembler-academy"
COMMON_DEPLOYMENT: "production"
