---

##
## Set up to allow a stateless app server and a stateful data server
## Can also be all on one server
## We might also want to have a single Badgr server that handles multiple clients, but 
## stores data separately
## 

- name: Configure Badgr data storage
  hosts: "badgr-sql-data-server"
  sudo: True
  gather_facts: True
  vars_files:
    - roles/common_vars/defaults/main.yml
  roles:
    - role: mysql_init
      mysql_databases: ["{{ BADGR_APP_MYSQL_DB_NAME | default('badgr_app') }}"]
      mysql_database_users: 
        - { db: "{{ BADGR_APP_MYSQL_DB_NAME | default('badgr_app') }}", 
            user: "{{ BADGR_APP_MYSQL_DB_USER | default('badgr001') }}", 
            pass: "{{ BADGR_APP_MYSQL_DB_PWD | default('NOTASECRET') }}"
          }

- name: Configure Badgr app
  hosts: "badgr-app-server"
  sudo: True
  gather_facts: True
  roles:
    - badgr
    - { role: nginx, nginx_sites: ["badgr"], vars_files: ["roles/badgr/defaults/main.yml"]}
    - { role: rbenv, rbenv_user: "{{ badgr_user }}", rbenv_dir: "{{ badgr_app_dir }}", rbenv_ruby_version: "{{ badgr_ruby_version }}" }
    - memcached
    - { role: rabbitmq, rabbitmq_ip: '127.0.0.1' }

