- name: Deploy all analytics services to a single node
  hosts: insights-server
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    disable_edx_services: false
    ENABLE_DATADOG: False
    ENABLE_SPLUNKFORWARDER: False
    ENABLE_NEWRELIC: False
    elasticsearch_repo: "deb http://packages.elasticsearch.org/elasticsearch/1.5/debian stable main"
    ELASTICSEARCH_VERSION: "1.5.2"
  roles:
    - sudo
    - aws
    - mysql_init
    - memcache
    - elasticsearch
    - analytics_api
    - analytics_pipeline
    - insights
    - role: nginx
      nginx_sites:
        - insights
    - insights_tracking_logs_sync
    - setup_pipeline
