---

# Appsembler pro tier deployment
# Docs: https://github.com/appsembler/openedx-docs/blob/master/openedx/pro_tier_deployment.md

- include: monitoring.yml

- name: Configure Mongo
  hosts: mongo-server
  become: True
  become_method: sudo
  gather_facts: True
  vars:
    BACKUPS_MONGO: yes
    BACKUPS_MYSQL: no
    COMMON_ENABLE_BACKUPS: True
  roles:
    - { role: swapfile, SWAPFILE_SIZE: "2GB" }
    - sudo
    - edxapp_common
    - mongo_3_0
    - oraclejdk
    - elasticsearch
    - memcached
    - backups

- name: Configure stateless edxapp instance
  hosts: edxapp-server
  sudo: True
  gather_facts: True
  vars:
    appsembler_roles: "../../../appsembler-roles"
    migrate_db: "yes"
    openid_workaround: True
    POSTGRESQL_AGGREGATION_INSTALL_CRON: true
  pre_tasks:
    # This is dirty, but better than setting in every server vars file
    - set_fact:
        EDXAPP_MONGO_SSL_CLIENT_CERT_PATH: "/edx/etc/edxapp/mongodb.pem"
        EDXAPP_MONGO_SSL_CA_CERT_PATH: "/edx/etc/edxapp/ca.pem"
      when: EDXAPP_MONGO_USE_SSL is defined and EDXAPP_MONGO_USE_SSL
      tags: always
  roles:
    - { role: swapfile, SWAPFILE_SIZE: "4GB" }
    - sudo
    - edxapp_common
    - mysql_init
    - role: nginx
      nginx_sites: []
    - role: "{{ appsembler_roles }}/letsencrypt"
      when: letsencrypt_certs | length
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      nginx_default_sites:
      - lms
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - role: edx_notes_api
      when: "INSTALL_EDX_NOTES is defined and INSTALL_EDX_NOTES"
    - role: demo
      when: "INSTALL_DEMO_DATA"
    - oauth_client_setup
    - forum
    - role: "githubsshkeys"
      when: "cloud_provider == 'azure'"
    - postgresql_aggregation

- name: Install xqueue, notifier and rabbitmq
  hosts: mongo-server
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
  roles:
    - mysql_init
    - role: nginx
      nginx_sites:
      - xqueue
    - { role: 'rabbitmq', rabbitmq_ip: '0.0.0.0' }
    - notifier
    - { role: notifier, NOTIFIER_DIGEST_TASK_INTERVAL: "5" }
    - { role: "xqueue", update_users: True }
    - role: "githubsshkeys"
      when: "cloud_provider == 'azure'"
