---

# Appsembler basic tier deployment

- include: monitoring.yml

- name: Configure basic tier instance
  hosts: edxapp-server
  become: True
  become_method: sudo
  gather_facts: True
  vars:
    appsembler_roles: "../../../appsembler-roles"
    migrate_db: "yes"
    SANDBOX_ENABLE_ECOMMERCE: False
    COMMON_ENABLE_INSIGHTS: False
    COMMON_ENABLE_OAUTH_CLIENT: False
    COMMON_ENABLE_BACKUPS: True
    POSTGRESQL_AGGREGATION_INSTALL_CRON: true
    ENABLE_ECOMMERCE: false
  roles:
    - { role: swapfile, SWAPFILE_SIZE: "4GB", tags: ['swapfile'] }
    - sudo
    - role: nginx
      nginx_sites: []
      tags: ['nginx']
    - role: "{{ appsembler_roles }}/letsencrypt"
      when: letsencrypt_certs | length
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      - xqueue
      - edx_notes_api
      nginx_default_sites:
      - lms
      tags: ['nginx']
    - { role: mysql, tags: ['mysql'] }
    - { role: mysql_init, tags: ['mysql_init'] }
    - role: memcache
      when: "'localhost' in ' '.join(EDXAPP_MEMCACHE)"
      tags: ['memcache']
    - role: mongo_3_0
      when: "'localhost' in EDXAPP_MONGO_HOSTS"
      tags: ['mongo_3_0']
    - { role: rabbitmq, rabbitmq_ip: '127.0.0.1', tags: ['rabbitmq'] }
    - { role: edxapp, celery_worker: True, tags: ['edxapp'] }
    - { role: edxapp, tags: ['edxapp'] }
    - { role: notifier, tags: ['notifier'] }
    - role: edx_notes_api
      when: "INSTALL_EDX_NOTES is defined and INSTALL_EDX_NOTES"
      tags: ['edx_notes_api']
    - role: demo
      when: "INSTALL_DEMO_DATA"
      tags: ['demo']
    - role: oauth_client_setup
      when: COMMON_ENABLE_OAUTH_CLIENT
      tags: ['oauth_client_setup']
    - { role: oraclejdk, tags: ['oraclejdk'] }
    - role: elasticsearch
      when: "'localhost' in EDXAPP_ELASTIC_SEARCH_CONFIG|map(attribute='host')"
      tags: ['elasticsearch']
    - { role: forum, tags: ['forum'] }
    - role: postgresql_aggregation
      when: COMMON_ENVIRONMENT == "prod"
      tags: ['postgresql_aggregation']
    - { role: notifier, NOTIFIER_DIGEST_TASK_INTERVAL: "5", tags: ['notifier'] }
    - { role: xqueue, update_users: True, tags: ['xqueue'] }
    - { role: backups, BACKUPS_MONGO: True, BACKUPS_MYSQL: True, when: COMMON_ENABLE_BACKUPS }
    - role: githubsshkeys
      when: "cloud_provider == 'azure'"
      tags: ['githubsshkeys']
    - role: ecommerce
      when: ENABLE_ECOMMERCE
      tags: ['ecommerce']
    - role: ecomworker
      when: ENABLE_ECOMMERCE
      tags: ['ecomworker']
    - role: ecommerce_theme
      when: ENABLE_ECOMMERCE
      tags: ['ecommerce_theme']
