---

# Appsembler pro tier deployment
# Docs: https://github.com/appsembler/openedx-docs/blob/master/openedx/pro_tier_deployment.md

- include: monitoring.yml

- name: Configure Mongo
  hosts: mongo-server
  become: True
  become_method: sudo
  gather_facts: True
  vars:
    BACKUPS_MONGO: yes
    BACKUPS_MYSQL: no
    COMMON_ENABLE_BACKUPS: True
  roles:
    - { role: swapfile, SWAPFILE_SIZE: "2GB", tags: ['swapfile'] }
    - sudo
    - { role: edxapp_common, tags: ['edxapp_common'] }
    - { role: mongo_3_0, tags: ['mongo_3_0'] }
    - { role: oraclejdk, tags: ['oraclejdk'] }
    - { role: elasticsearch, tags: ['elasticsearch'] }
    - { role: memcached, tags: ['memcached'] }
    - backups

- name: Configure stateless edxapp instance
  hosts: edxapp-server
  sudo: True
  gather_facts: True
  vars:
    appsembler_roles: "../../../appsembler-roles"
    migrate_db: "yes"
    openid_workaround: True
    POSTGRESQL_AGGREGATION_INSTALL_CRON: true
    ENABLE_ECOMMERCE: false
  pre_tasks:
    # This is dirty, but better than setting in every server vars file
    - set_fact:
        EDXAPP_MONGO_SSL_CLIENT_CERT_PATH: "/edx/etc/edxapp/mongodb.pem"
        EDXAPP_MONGO_SSL_CA_CERT_PATH: "/edx/etc/edxapp/ca.pem"
      when: EDXAPP_MONGO_USE_SSL is defined and EDXAPP_MONGO_USE_SSL
      tags: always
  roles:
    - { role: swapfile, SWAPFILE_SIZE: "4GB", tags: ['swapfile'] }
    - sudo
    - { role: edxapp_common, tags: ['edxapp_common'] }
    - { role: mysql_init, tags: ['mysql_init'] }
    - role: nginx
      nginx_sites: []
      tags: ['nginx']
    - role: "{{ appsembler_roles }}/letsencrypt"
      when: letsencrypt_certs | length
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      nginx_default_sites:
      - lms
      tags: ['nginx']
    - { role: edxapp, celery_worker: True, tags: ['edxapp'] }
    - { role: edxapp, tags: ['edxapp'] }
    - role: edx_notes_api
      when: "INSTALL_EDX_NOTES is defined and INSTALL_EDX_NOTES"
      tags: ['edx_notes_api']
    - role: demo
      when: "INSTALL_DEMO_DATA"
      tags: ['demo']
    - { role: oauth_client_setup, tags: ['oauth_client_setup'] }
    - { role: forum, tags: ['forum'] }
    - role: githubsshkeys
      when: "cloud_provider == 'azure'"
      tags: ['githubsshkeys']
    - role: postgresql_aggregation
      when: COMMON_ENVIRONMENT == "prod"
      tags: ['postgresql_aggregation']
    - role: ecommerce
      when: ENABLE_ECOMMERCE
      tags: ['ecommerce']
    - role: ecomworker
      when: ENABLE_ECOMMERCE
      tags: ['ecomworker']
    - role: ecommerce_theme
      when: ENABLE_ECOMMERCE
      tags: ['ecommerce_theme']

- name: Install xqueue, notifier and rabbitmq
  hosts: mongo-server
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
  roles:
    - { role: mysql_init, tags: ['mysql_init'] }
    - role: nginx
      nginx_sites:
      - xqueue
      tags: ['nginx']
    - { role: rabbitmq, rabbitmq_ip: '0.0.0.0', tags: ['rabbitmq'] }
    - { role: notifier, tags: ['notifier'] }
    - { role: notifier, NOTIFIER_DIGEST_TASK_INTERVAL: "5", tags: ['notifier'] }
    - { role: xqueue, update_users: True, tags: ['xqueue'] }
    - role: githubsshkeys
      when: "cloud_provider == 'azure'"
      tags: ['githubsshkeys']
