- name: Deploy all analytics services to a single node
  hosts: insights-server
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    disable_edx_services: false
    ENABLE_DATADOG: False
    ENABLE_SPLUNKFORWARDER: False
    ENABLE_NEWRELIC: False
    elasticsearch_repo: "deb http://packages.elasticsearch.org/elasticsearch/1.5/debian stable main"
    ELASTICSEARCH_VERSION: "1.5.2"
  roles:
    - sudo
    - { role: aws, tags: ['aws'] }
    - { role: mysql_init, tags: ['mysql_init'] }
    - { role: memcache, tags: ['memcache'] }
    - { role: elasticsearch, tags: ['elasticsearch'] }
    - { role: analytics_api, tags: ['analytics_api'] }
    - { role: analytics_pipeline, tags: ['analytics_pipeline'] }
    - { role: insights, tags: ['insights'] }
    - role: nginx
      nginx_sites:
        - insights
      tags: ['nginx']
    - { role: insights_tracking_logs_sync, tags: ['insights_tracking_logs_sync'] }
    - { role: setup_pipeline, tags: ['setup_pipeline'] }
