---
# for single server community
# This file based on `edx_sandbox.yml`

- name: Configure instance(s)
  hosts: edxapp-server
  sudo: True
  gather_facts: True
  vars:
    POSTGRESQL_AGGREGATION_INSTALL_CRON: false
  roles:
    - sudo
    - postgresql_aggregation
