- name: Deploy edX Notes API
  hosts: edxapp-server
  become: True
  gather_facts: True
  vars:
    ENABLE_DATADOG: False
    ENABLE_SPLUNKFORWARDER: False
    ENABLE_NEWRELIC: False
  roles:
    - mysql_init
    - role: nginx
      nginx_sites:
        - edx_notes_api
    - edx_notes_api 
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
