---
# for single server community
# This file based on `edx_sandbox.yml`

- name: Update theme
  hosts: edxapp-server
  become: True
  gather_facts: True
  vars_files:
  - roles/common_vars/defaults/main.yml
  - roles/supervisor/defaults/main.yml
  - roles/edxapp/defaults/main.yml
  vars:
    tmp: none
  tasks:
    - name: install read-only ssh key
      copy:
        content: "{{ EDXAPP_GIT_IDENTITY }}"
        dest: "{{ edxapp_git_identity }}"
        force: yes
        owner: "{{ edxapp_user }}"
        mode: "0600"
      when: EDXAPP_USE_GIT_IDENTITY
      tags:
        - install
        - install:base
        - deploy:platform

    - name: copy the template to the desired location
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      with_items:
        - { src: 'roles/edxapp/templates/git_ssh.sh.j2', dest: '{{ edxapp_git_ssh }}', owner: '{{ edxapp_user }}', group: '{{ edxapp_user }}', mode: '0750' }
      tags:
        - install
        - install:base

    - name: checkout Stanford-style theme
      git_2_0_1:
        dest: "{{ edxapp_app_dir }}/themes/{{ edxapp_theme_name }}"
        repo: "{{ edxapp_theme_source_repo }}"
        version: "{{ edxapp_theme_version }}"
        accept_hostkey: yes
      when: edxapp_theme_name != ''
      become_user: "{{ edxapp_user }}"
      environment:
        GIT_SSH: "{{ edxapp_git_ssh }}"
      register: edxapp_theme_checkout
      tags:
        - install
        - install:code

    - name: checkout comprehensive theme
      git_2_0_1:
        dest: "{{ edxapp_theme_dir }}/{{ EDXAPP_DEFAULT_SITE_THEME }}"
        repo: "{{ edxapp_theme_source_repo }}"
        version: "{{ edxapp_theme_version }}"
        accept_hostkey: yes
      when: EDXAPP_ENABLE_COMPREHENSIVE_THEMING == true and EDXAPP_DEFAULT_SITE_THEME != ''
      become_user: "{{ edxapp_user }}"
      environment:
        GIT_SSH: "{{ edxapp_git_ssh }}"
      register: edxapp_theme_checkout
      tags:
        - install
        - install:code

    - name: checkout customer override theme
      git_2_0_1:
        dest: "{{ edxapp_theme_dir }}/{{ EDXAPP_DEFAULT_SITE_THEME }}/customer_specific"
        repo: "{{ edxapp_customer_theme_source_repo }}"
        version: "{{ edxapp_customer_theme_version }}"
        accept_hostkey: yes
        key_file: "/edx/app/edxapp/.ssh/id_rsa"
      when: EDXAPP_ENABLE_COMPREHENSIVE_THEMING == true and edxapp_customer_theme_source_repo != ''
      become_user: "{{ edxapp_user }}"
      environment:
        GIT_SSH: "{{ edxapp_git_ssh }}"
      tags:
        - install
        - install:code

    - name: remove read-only ssh key
      file:
        path: "{{ edxapp_git_identity }}"
        state: absent
      when: EDXAPP_USE_GIT_IDENTITY
      tags:
        - install
        - install:configuration
        - install:code
        - deploy:platform

    - name: Remove and recreate the staticfiles directory so nothing stale can exist
      file:
          path: "{{ edxapp_staticfile_dir }}"
          state: "{{ item }}"
          owner: "{{ edxapp_user }}"
          group: "{{ common_web_group }}"
          mode:  "0755"
      when: celery_worker is not defined and not devstack
      with_items: ['absent', 'directory']
      tags:
        - gather_static_assets
        - assets

    # Gather assets using paver if possible
    - name: "gather {{ item }} static assets with paver"
      command: "{{ COMMON_BIN_DIR }}/edxapp-update-assets-{{ item }}"
      when: celery_worker is not defined and not devstack and item != "lms-preview"
      with_items: "{{ service_variants_enabled }}"
      tags:
        - gather_static_assets
        - assets

    - name: restart LMS
      supervisorctl:
        name: "edxapp:lms"
        supervisorctl_path: "{{ supervisor_ctl }}"
        config: "{{ supervisor_cfg }}"
        state: restarted
      become_user: "{{ supervisor_service_user }}"
      when: celery_worker is not defined and not disable_edx_services
      tags:
        - manage

    - name: restart CMS
      supervisorctl:
        name: "edxapp:cms"
        supervisorctl_path: "{{ supervisor_ctl }}"
        config: "{{ supervisor_cfg }}"
        state: restarted
      become_user: "{{ supervisor_service_user }}"
      when: celery_worker is not defined and not disable_edx_services
      tags:
        - manage

    - name: ensure edxapp has started
      supervisorctl:
        name: "edxapp:"
        supervisorctl_path: "{{ supervisor_ctl }}"
        config: "{{ supervisor_cfg }}"
        state: started
      become_user: "{{ supervisor_service_user }}"
      when: celery_worker is not defined and not disable_edx_services
      tags:
        - manage
