EDXAPP_PLATFORM_NAME: 'Docker'
EDXAPP_LMS_NGINX_PORT: 80

# Mongo DB
EDXAPP_MONGO_HOSTS: ['mongodb']
EDXAPP_MONGO_PORT: 27017
EDXAPP_MONGO_DB_NAME: 'docker-edxapp'
EDXAPP_MONGO_USER: 'edxapp'
EDXAPP_MONGO_PASSWORD: 'daheiYae2c'
MONGO_BIND_IP: '0.0.0.0'
mongo_create_users: true
