---

- name: Configure instance(s)
  hosts: edx
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
    # These should stay false for the public AMI
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
  vars_files:
    - vault/production_secret_vars.yml
  tasks:
    - name: install memcached
      apt: pkg=memcached state=present
  roles:
    - { role: swapfile, SWAPFILE_SIZE: "2GB" }
    - role: scorm
      when: "{{ EDXAPP_XBLOCK_SETTINGS }}.get('ScormXBlock', False)"
      tags: deploy
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - forum
      - xqueue
      - edx_notes_api
      nginx_default_sites:
      - lms
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - notifier
    - analytics_api
    - analytics_pipeline
    - insights
    - edx_notes_api
    - demo
    - {
        role: 'demo',
        demo_code_dir: "{{ demo_app_dir }}/test101",
        demo_repo: "https://github.com/cptvitamin/demo-test-course",
        demo_course_id: "course-v1:edX+Test101+course",
        tags: 'demo_test101',
      }
    - oauth_client_setup
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - oraclejdk
    - role: elasticsearch
      when: "'localhost' in EDXAPP_ELASTIC_SEARCH_CONFIG|map(attribute='host')"
    - forum
    - { role: notifier, NOTIFIER_DIGEST_TASK_INTERVAL: "5" }
    - { role: "xqueue", update_users: True }
    - certs
    - edx_ansible
    - { role: swapfile, SWAPFILE_SIZE: "2GB" }
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
