- name: Deploy edxapp
  hosts: all
  sudo: True
  gather_facts: True
  roles:
    - { role: 'docker', runit_service: 'supervisor' }
    - { role: 'docker', runit_service: 'memcached' }
    - role: nginx
      nginx_sites:
      - lms
      - cms
      nginx_default_sites:
      - lms
    - edxapp
    - { role: 'docker', runit_service: 'supervisor' }
    - { role: 'docker', runit_service: 'memcached' }
