---

- name: Configure instance(s)
  hosts: mongo
  sudo: True
  gather_facts: True
  vars:
    MONGO_CLUSTERED: True
    # The following should be overriden to create a replica set:
    # MONGO_CLUSTER_KEY: ''
    # mongo_repl_set: ''
    # mongo_cluster_members: []
  roles:
    - mongo
