---

# Example sandbox configuration
# for single server community
# installs

- name: Install monitoring on nodes
  hosts: all
  sudo: True
  gather_facts: True
  roles:
    - role: sysdig
#    - role: stackdriver
