---

- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars_files:
    - roles/edxapp/defaults/main.yml
    - roles/xqueue/defaults/main.yml
    - roles/ora/defaults/main.yml
    - roles/analytics-api/defaults/main.yml
  vars:
    MYSQL_BIND_IP: 0.0.0.0
    MYSQL_USER_HOST: '%'
  roles:
    - { role: 'docker', runit_service: 'mysql', stop_services: true }
    - edxlocal
    - { role: 'docker', runit_service: 'mysql' }
