---

# This play should run locally and target a remote MySQL instance by setting
# mysql_login_user, mysql_login_password, mysql_login_host, and
# mysql_login_port
- name: Configure mysql DBs and users
  hosts: mysql_init
  sudo: False
  gather_facts: False
  vars_files:
    - roles/analytics_api/defaults/main.yml
    - roles/analytics_pipeline/defaults/main.yml
    - roles/common_vars/defaults/main.yml
    - roles/ecommerce/defaults/main.yml
    - roles/edxapp/defaults/main.yml
    - roles/edx_notes_api/defaults/main.yml
    - roles/hive/defaults/main.yml
    - roles/insights/defaults/main.yml
    - roles/programs/defaults/main.yml
    - roles/xqueue/defaults/main.yml
    - vault/production_secret_vars.yml
    - hosts/amc_production/group_vars/all
    - hosts/amc_production/group_vars/mysql_init
  roles:
    - mysql_init
