---

- name: Configure instance(s)
  hosts: all
  gather_facts: True
  vars_files:
    - roles/common/defaults/main.yml
    - roles/edxapp/defaults/main.yml
    - roles/xqueue/defaults/main.yml
    - roles/ora/defaults/main.yml
    - roles/analytics_api/defaults/main.yml
  roles:
    - mysql
