---

- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  roles:
    - role: nginx
      nginx_sites:
      - xqueue
    - { role: 'xqueue', disable_edx_services: True }
    - { role: 'docker', runit_service: 'xqueue' }
    - { role: 'docker', runit_service: 'nginx' }
