---

- name: checkout customer override theme
  git_2_0_1:
    dest: "{{ edxapp_app_dir }}/themes/{{ edxapp_theme_name }}/customer_specific"
    repo: "{{ edxapp_customer_theme_source_repo }}"
    version: "{{ edxapp_customer_theme_version }}"
    accept_hostkey: yes
    key_file: "/edx/app/edxapp/.ssh/id_rsa"
  when: EDXAPP_ENABLE_COMPREHENSIVE_THEMING == true
  become_user: "{{ edxapp_user }}"
  environment:
    GIT_SSH: "{{ edxapp_git_ssh }}"
  tags:
    - install
    - install:code
