---

- name: checkout comprehensive theme
  git_2_0_1:
    dest: "{{ edxapp_theme_dir }}/{{ edxapp_theme_name }}"
    repo: "{{ edxapp_theme_source_repo }}"
    version: "{{ edxapp_theme_version }}"
    accept_hostkey: yes
  when: EDXAPP_ENABLE_COMPREHENSIVE_THEMING == true and edxapp_theme_name != ''
  become_user: "{{ edxapp_user }}"
  environment:
    GIT_SSH: "{{ edxapp_git_ssh }}"
  register: edxapp_theme_checkout
  tags:
    - install
    - install:code

- name: checkout customer override theme
  git_2_0_1:
    dest: "{{ edxapp_theme_dir }}/{{ edxapp_theme_name }}/customer_specific"
    repo: "{{ edxapp_customer_theme_source_repo }}"
    version: "{{ edxapp_customer_theme_version }}"
    accept_hostkey: yes
    key_file: "/edx/app/edxapp/.ssh/id_rsa"
  when: EDXAPP_ENABLE_COMPREHENSIVE_THEMING == true and edxapp_customer_theme_source_repo != ''
  become_user: "{{ edxapp_user }}"
  environment:
    GIT_SSH: "{{ edxapp_git_ssh }}"
  tags:
    - install
    - install:code
